### ISSUE TITLE
其实一共是有160张的。。

### ISSUE THREAD

**Issue by DavidDiao** [a-wing/Menhera-chan#1]
这套表情一共有四套
 - メンヘラちゃん。
 - メンヘラちゃん。２
 - メンヘラ少女。
 - メンヘラ少女。2

（句号是名字的一部分，前面一个2是全角，后面一个是半角）
每套40张

「メンヘラちゃん。」是长发，「メンヘラ少女。」是短发，不过两套有不少是一样的，差别只是头发，所以可能当成同样的删掉了？

比如两套的第一张
![image](https://user-images.githubusercontent.com/21342724/38895206-57701bda-42ca-11e8-997a-6100fa2b4814.png)
![image](https://user-images.githubusercontent.com/21342724/38895236-6d3b18ac-42ca-11e8-949a-b6f41e7f8d4c.png)

~~我只有250x版本的所以别问我要啦~~

**Comment by a-wing** [comment]
特意去查了下 的确是 160 张（加上英文版，总计应该是320 张）。

删除的的是从其他地方弄来的版本，都是这120张了重复的

网上流传的版本里没有

Menhera little girl. 2
