### ISSUE TITLE
新的一套又出来了,加上之前的linestore版本未放大高清原版

### ISSUE THREAD

**Issue by ZYFDroid** [a-wing/Menhera-chan#10]
新的一套是动图,一共24张.这次就懒得搞pull request了,直接附件
[MenheraTwins.zip](https://github.com/a-wing/Menhera-chan/files/2039974/MenheraTwins.zip)

**Comment by a-wing** [comment]
Added 3c6e4f3107f66f16a372964845da99fdd128e992
