### ISSUE TITLE
顺便把全部的英文版的也从line上提取了一下

### ISSUE THREAD

**Issue by ZYFDroid** [a-wing/Menhera-chan#11]
line提取版，除了MenheraChan4以外都有。因为4是动图，翻译耗时间。这次提取的版本至少更清晰了一些，可以理解为标清版(和我之前上传的是同一个分辨率)，还顺手写了个readme
[MenheraTwins.zip](https://github.com/a-wing/Menhera-chan/files/2041857/MenheraTwins.zip)

**Comment by ZYFDroid** [comment]
readme里面的文本可以做一些必要的修改和润色。我语文完全不行，外加社交障碍，写出来的文本内容可能需要进行调整

**Comment by ZYFDroid** [comment]
我发布了一个Line表情包提取器，无需安装line，只需有网和翻墙就能提取的那种。可以到我的仓库看看

**Comment by a-wing** [comment]
棒棒哒QAQ

**Comment by a-wing** [comment]
added 7a78235e4ba94fc8f41c6d34336f1de095e9845e
