### ISSUE TITLE
第四套英文版

### ISSUE THREAD

**Issue by ZYFDroid** [a-wing/Menhera-chan#12]
放文件不解释(建议Readme里加一条:看不到动态效果的请用chrome打开图片)

[NanaseKonomi4_EN.zip](https://github.com/a-wing/Menhera-chan/files/2048260/NanaseKonomi4_EN.zip)

**Comment by a-wing** [comment]
要不？提pr吧。。。commit 的都是我名有点过意不去了。。。

**Comment by ZYFDroid** [comment]
我懒

**Comment by a-wing** [comment]
Added 57aeadcef28a29c2a3cc43fb309dce28c79057a8
