### ISSUE TITLE
Menhera-chan.5

### ISSUE THREAD

**Issue by a-wing** [a-wing/Menhera-chan#14]
![79bf1cd9-d460-456f-8045-4f908dc4bdd2](https://user-images.githubusercontent.com/18189138/41166149-12391b68-6b72-11e8-9829-cfa548dfe226.jpeg)

**Comment by ZYFDroid** [comment]
已下载。在我的其中一个仓库里有

**Comment by ZYFDroid** [comment]
[3805102.zip](https://github.com/a-wing/Menhera-chan/files/2090171/3805102.zip)

**Comment by ZYFDroid** [comment]
鬼天气表情包系列😂

**Comment by a-wing** [comment]
Added 171ecb8af49ef9ca3b139b7848e91795fe67c5f0

**Comment by a-wing** [comment]
怎么感觉这个有点毁形象啊。。。
