### ISSUE TITLE
第五套英文版

### ISSUE THREAD

**Issue by ZYFDroid** [a-wing/Menhera-chan#15]
前几天刚刚更新

[NanaseKurumi5_EN.zip](https://github.com/a-wing/Menhera-chan/files/2126297/NanaseKurumi5_EN.zip)

话说要不要考虑看看作者的其它作品

**Comment by a-wing** [comment]
Added d2e062466cce105f7c6253a83e538e359eac706a

**Comment by a-wing** [comment]
@ZYFDroid 
![dgmuqhpuwaamicn](https://user-images.githubusercontent.com/18189138/41758698-0419f330-761d-11e8-9c68-75d10fc73b5d.jpg)

这种还好。。猫娘狗娘就算了吧

漫画。。。。。

都有点跟不上作者创造的速度了。。。。
