### ISSUE TITLE
Telegram Menhera

### ISSUE THREAD

**Issue by seiya-git** [a-wing/Menhera-chan#20]
Links:

Japanese:
https://t.me/addstickers/LINE_Menhera_chan
https://t.me/addstickers/LINE_Menhera_chan_2
https://t.me/addstickers/LINE_Menhera_little_girl

English:
https://t.me/addstickers/LINE_Menhera_chan_ENG
https://t.me/addstickers/LINE_Menhera_chan_2_ENG
https://t.me/addstickers/LINE_Menhera_little_girl_ENG

P.S.
https://t.me/addstickers/Menhera_chanwww - not work anymore

**Comment by a-wing** [comment]
Nice !
Added 7730b5aa015929fa3a4b46d8cbdcbc1fb51fe0c2
