### ISSUE TITLE
第六套，英文版也出了

### ISSUE THREAD

**Issue by ZYFDroid** [a-wing/Menhera-chan#23]
估计不久之后徒手汉化版也会跟进

**Comment by ZYFDroid** [comment]
目前因为commit的更改导致两个brunch合不起来，不能通过提pull request的方法更新

**Comment by a-wing** [comment]
其实可以。。。导出新提交的patch。clone 我的仓库。patch上代码。然后提交。push -f 推送到自己的仓库之后。然后提pr

**Comment by ZYFDroid** [comment]
网络不行。你可以手动把我fork的仓库手动合并一下

**Comment by a-wing** [comment]
Added a7374e91fa11683ad82c579b7f46699ce9eacba4
