### ISSUE TITLE
What ? メンヘラちゃん。の秋スタンプできたよ～～～

### ISSUE THREAD

**Issue by a-wing** [a-wing/Menhera-chan#28]
![dnbmygpu0aa5rug jpg large](https://user-images.githubusercontent.com/18189138/45791781-b701f600-bcbd-11e8-9725-53beadef6645.jpg)

怎么又来了个 `6` 啊。。。。

**Comment by ZYFDroid** [comment]
你已经有了一个下载工具了，应该学会自己更新了
