### ISSUE TITLE
An example of Waifu2x processed image.

### ISSUE THREAD

**Issue by ZYFDroid** [a-wing/Menhera-chan#33]
![85738889](https://user-images.githubusercontent.com/39429452/46681331-99b9ab00-cc1d-11e8-9587-992126a6f0c0.png)
4 times resolution example.(since Waifu2x is not good at deal with alpha channel. The edge is still blurred)

**Comment by ZYFDroid** [comment]
I have a method to prevent the blurred edge, but now it need to be manually processed.

**Comment by ZYFDroid** [comment]
An example of the process of preventing blurred edge.
![perfect](https://user-images.githubusercontent.com/39429452/46905546-fd96e900-cf27-11e8-90ee-b7639570471f.png)

**Comment by ZYFDroid** [comment]
I will write a C# Program to process such pictures with waifu2x console

**Comment by a-wing** [comment]
Why is use C# ？

**Comment by ZYFDroid** [comment]
Use c# for batch process, or I need to process each image manually with Photoshop.

**Comment by simon300000** [comment]
I submitted a pr #7 before with all picture waifu2x, It is not a good idea...

**Comment by ZYFDroid** [comment]
@simon300000 
Directly use waifu2x will cause the blurred edge. Some special methods is used to prevent this problem. (Please compare the two pictures above.)

**Comment by simon300000** [comment]
I did not observe such a big blur after zooming with waifu2x?
Or I didn't find it...
A example output of waifu2x directly: https://github.com/a-wing/Menhera-chan/blob/2a099d1139b11751fbadbe60f1653bba891385d1/waifu2x/from_tieba_yun_baidu/menhera_little_girl_2_Neil.M/121.png

**Comment by ZYFDroid** [comment]
Maybe I'm using a fake waifu2x
![1539505945654](https://user-images.githubusercontent.com/39429452/46914365-de06cb80-cfce-11e8-8567-8fc3af233c35.jpg)
