### ISSUE TITLE
第九套，了解一下

### ISSUE THREAD

**Issue by ZYFDroid** [a-wing/Menhera-chan#39]
你已经是个成熟的仓库了，该学会自己更新了

**Comment by a-wing** [comment]
_(ˊཀˋ」∠)_

**Comment by ZYFDroid** [comment]
备赛，忙，早出了，今天才想起来

**Comment by ZYFDroid** [comment]
加这个群，如果实在不会抓图的话，这个群有更新
215745541

**Comment by a-wing** [comment]
我自己去弄不是就放在我的目录下了吗（。。。。为了一致性还是你来 PR 吧 ：）

**Comment by a-wing** [comment]
更新了 两套。。。。我有点蒙。。好像还少几套 （有时间仔细核对一下）
