### ISSUE TITLE
新的一套又出来了

### ISSUE THREAD

**Issue by ZYFDroid** [a-wing/Menhera-chan#4]
建议去line上看看

**Comment by KellyHwong** [comment]
好棒，GitHub船新玩法，众包表情包_(:з」∠)_

**Comment by a-wing** [comment]
作者今天刚发了推特 https://twitter.com/pomujoynet1/status/998749553883951106

Menhera-chan.4 要出了

突然发现你说的的新的一套，是指Menhera-chan.3 还是Menhera-chan.4 啊。。

**Comment by ZYFDroid** [comment]
一共有五个版本
Menhera Chan1-3，每套40张，共120张。
Menhera Little Girl 1-2，每套40张，共80张
网上的分类目前是错误的，把Little Girl的第一套和Chan第一第二套混在一起了，我那边仓库里区分了一下

**Comment by ZYFDroid** [comment]
4出了之后我去弄下来。最近研究了个Line贴纸表情下载器。今晚发GitHub

**Comment by simon300000** [comment]
→_→ 可以 pull request 哦

**Comment by KellyHwong** [comment]
@ZYFDroid @a-wing @simon300000 皆んな、那就是说一共200张咯，我这里有个版本，怎么有340多张，貌似还是中日英三语_(:з」∠)_

**Comment by KellyHwong** [comment]
<img width="538" alt="cnjpen-menhera" src="https://user-images.githubusercontent.com/5453534/40362453-2d8ab7e4-5dff-11e8-8ca8-f43b9a47da07.png">
这里

**Comment by simon300000** [comment]
好啊好啊 对比一下，没有的直接pull request进来
这边这个英语的质量很低

**Comment by KellyHwong** [comment]
好滴（第一次PR给了menhera。。。开心）

**Comment by a-wing** [comment]
感觉 Review 你们发过来的东西比我自己去收集还累。。。。。

**Comment by a-wing** [comment]
@ZYFDroid 网上流传的分类有一些历史遗留问题
